export { Home } from './home/home'
export { NotFound } from './not-found/not-found'
export { Login } from './login/login'
export { Register } from './register/register'
export { ForgotPassword } from './forgot-password/forgot-password'
export { ResetPassword } from './reset-password/reset-password'
export { Profile } from './profile/profile'
export { Feed } from './feed/feed'
