export { Home } from './home/home'
export { NotFound } from './not-found/not-found'
export { Login } from './login/login'
export { Register } from './register/register'
export { ForgotPassword } from './forgot-password/forgot-password'
